/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    PortfolioTracker: {
      address: "0x7a2088a1bFc9d81c55368AE168C2C02570cB814F",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "previousAdmin",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "AdminChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "beacon",
              type: "address",
            },
          ],
          name: "BeaconUpgraded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "implementation",
              type: "address",
            },
          ],
          name: "Upgraded",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "implementation",
              type: "address",
            },
          ],
          name: "ERC1967InvalidImplementation",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC1967NonPayable",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidInitialization",
          type: "error",
        },
        {
          inputs: [],
          name: "NotInitializing",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [],
          name: "UUPSUnauthorizedCallContext",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "slot",
              type: "bytes32",
            },
          ],
          name: "UUPSUnsupportedProxiableUUID",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "AssetClassAssigned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ClassCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "ClassDeactivated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ClassRenamed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint64",
              name: "version",
              type: "uint64",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceUsdScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
          ],
          name: "ManualPriceSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "avgBuyPriceScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "stakingRewardsScaled",
              type: "uint256",
            },
          ],
          name: "PositionSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: true,
              internalType: "address",
              name: "feed",
              type: "address",
            },
          ],
          name: "PriceFeedSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceUsdScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "realizedPnlDelta",
              type: "int256",
            },
          ],
          name: "SellRecorded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "extraRewardsScaled",
              type: "uint256",
            },
          ],
          name: "StakingRewardsAdded",
          type: "event",
        },
        {
          inputs: [],
          name: "ASSET_COUNT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SCALE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "UPGRADE_INTERFACE_VERSION",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "extraRewardsScaled",
              type: "uint256",
            },
          ],
          name: "addStakingRewards",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "assetClassId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "assetClasses",
          outputs: [
            {
              internalType: "enum PortfolioTracker.AssetClass",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "createClass",
          outputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "deactivateClass",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
          ],
          name: "getAssetReport",
          outputs: [
            {
              components: [
                {
                  internalType: "uint8",
                  name: "asset",
                  type: "uint8",
                },
                {
                  internalType: "enum PortfolioTracker.AssetClass",
                  name: "assetClass",
                  type: "uint8",
                },
                {
                  internalType: "bool",
                  name: "hasPosition",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "priceOk",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "usingManualPrice",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "priceUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "principalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "stakingRewards",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "costUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "valueUsd",
                  type: "uint256",
                },
                {
                  internalType: "int256",
                  name: "pnlUsd",
                  type: "int256",
                },
                {
                  internalType: "bool",
                  name: "inProfit",
                  type: "bool",
                },
              ],
              internalType: "struct PortfolioTracker.AssetReport",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "getClassInfo",
          outputs: [
            {
              internalType: "bool",
              name: "exists",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getPortfolioReport",
          outputs: [
            {
              components: [
                {
                  internalType: "uint8",
                  name: "asset",
                  type: "uint8",
                },
                {
                  internalType: "enum PortfolioTracker.AssetClass",
                  name: "assetClass",
                  type: "uint8",
                },
                {
                  internalType: "bool",
                  name: "hasPosition",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "priceOk",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "usingManualPrice",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "priceUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "principalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "stakingRewards",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "costUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "valueUsd",
                  type: "uint256",
                },
                {
                  internalType: "int256",
                  name: "pnlUsd",
                  type: "int256",
                },
                {
                  internalType: "bool",
                  name: "inProfit",
                  type: "bool",
                },
              ],
              internalType: "struct PortfolioTracker.AssetReport[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "initialize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "initializeV2",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "lastSellAmount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "lastSellPriceUsd",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "manualPriceUsd",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextClassId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "positions",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "avgBuyPrice",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "stakingRewards",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "priceFeeds",
          outputs: [
            {
              internalType: "contract AggregatorV3Interface",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proxiableUUID",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "realizedPnlUsd",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "sellAmountScaled",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sellPriceUsdScaled",
              type: "uint256",
            },
          ],
          name: "recordSell",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "renameClass",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
          ],
          name: "safeGetPriceUsdScaled",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "setAssetClass",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "priceUsdScaled",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
          ],
          name: "setManualPrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "amountScaled",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "avgBuyPriceScaled",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "stakingRewardsScaled",
              type: "uint256",
            },
          ],
          name: "setPosition",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "feed",
              type: "address",
            },
          ],
          name: "setPriceFeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newImplementation",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "upgradeToAndCall",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "useManualPrice",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_logic",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
          ],
          stateMutability: "payable",
          type: "constructor",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 31,
    },
    PortfolioTracker_Implementation: {
      address: "0x4A679253410272dd5232B3Ff7cF5dbB88f295319",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "implementation",
              type: "address",
            },
          ],
          name: "ERC1967InvalidImplementation",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC1967NonPayable",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidInitialization",
          type: "error",
        },
        {
          inputs: [],
          name: "NotInitializing",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [],
          name: "UUPSUnauthorizedCallContext",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "slot",
              type: "bytes32",
            },
          ],
          name: "UUPSUnsupportedProxiableUUID",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "AssetClassAssigned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ClassCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "ClassDeactivated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ClassRenamed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint64",
              name: "version",
              type: "uint64",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceUsdScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
          ],
          name: "ManualPriceSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "avgBuyPriceScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "stakingRewardsScaled",
              type: "uint256",
            },
          ],
          name: "PositionSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: true,
              internalType: "address",
              name: "feed",
              type: "address",
            },
          ],
          name: "PriceFeedSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceUsdScaled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "realizedPnlDelta",
              type: "int256",
            },
          ],
          name: "SellRecorded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint8",
              name: "asset",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "extraRewardsScaled",
              type: "uint256",
            },
          ],
          name: "StakingRewardsAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "implementation",
              type: "address",
            },
          ],
          name: "Upgraded",
          type: "event",
        },
        {
          inputs: [],
          name: "ASSET_COUNT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SCALE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "UPGRADE_INTERFACE_VERSION",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "extraRewardsScaled",
              type: "uint256",
            },
          ],
          name: "addStakingRewards",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "assetClassId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "assetClasses",
          outputs: [
            {
              internalType: "enum PortfolioTracker.AssetClass",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "createClass",
          outputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "deactivateClass",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
          ],
          name: "getAssetReport",
          outputs: [
            {
              components: [
                {
                  internalType: "uint8",
                  name: "asset",
                  type: "uint8",
                },
                {
                  internalType: "enum PortfolioTracker.AssetClass",
                  name: "assetClass",
                  type: "uint8",
                },
                {
                  internalType: "bool",
                  name: "hasPosition",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "priceOk",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "usingManualPrice",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "priceUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "principalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "stakingRewards",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "costUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "valueUsd",
                  type: "uint256",
                },
                {
                  internalType: "int256",
                  name: "pnlUsd",
                  type: "int256",
                },
                {
                  internalType: "bool",
                  name: "inProfit",
                  type: "bool",
                },
              ],
              internalType: "struct PortfolioTracker.AssetReport",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "getClassInfo",
          outputs: [
            {
              internalType: "bool",
              name: "exists",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getPortfolioReport",
          outputs: [
            {
              components: [
                {
                  internalType: "uint8",
                  name: "asset",
                  type: "uint8",
                },
                {
                  internalType: "enum PortfolioTracker.AssetClass",
                  name: "assetClass",
                  type: "uint8",
                },
                {
                  internalType: "bool",
                  name: "hasPosition",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "priceOk",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "usingManualPrice",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "priceUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "principalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "stakingRewards",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "costUsd",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "valueUsd",
                  type: "uint256",
                },
                {
                  internalType: "int256",
                  name: "pnlUsd",
                  type: "int256",
                },
                {
                  internalType: "bool",
                  name: "inProfit",
                  type: "bool",
                },
              ],
              internalType: "struct PortfolioTracker.AssetReport[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "initialize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "initializeV2",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "lastSellAmount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "lastSellPriceUsd",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "manualPriceUsd",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextClassId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "positions",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "avgBuyPrice",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "stakingRewards",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "priceFeeds",
          outputs: [
            {
              internalType: "contract AggregatorV3Interface",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proxiableUUID",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "realizedPnlUsd",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "sellAmountScaled",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sellPriceUsdScaled",
              type: "uint256",
            },
          ],
          name: "recordSell",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "renameClass",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
          ],
          name: "safeGetPriceUsdScaled",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "classId",
              type: "uint256",
            },
          ],
          name: "setAssetClass",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "priceUsdScaled",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
          ],
          name: "setManualPrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "amountScaled",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "avgBuyPriceScaled",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "stakingRewardsScaled",
              type: "uint256",
            },
          ],
          name: "setPosition",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "asset",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "feed",
              type: "address",
            },
          ],
          name: "setPriceFeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newImplementation",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "upgradeToAndCall",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PortfolioTracker.AssetId",
              name: "",
              type: "uint8",
            },
          ],
          name: "useManualPrice",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 29,
    },
    PortfolioTracker_Proxy: {
      address: "0x7a2088a1bFc9d81c55368AE168C2C02570cB814F",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_logic",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
          ],
          stateMutability: "payable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "previousAdmin",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "AdminChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "beacon",
              type: "address",
            },
          ],
          name: "BeaconUpgraded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "implementation",
              type: "address",
            },
          ],
          name: "Upgraded",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 31,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
